<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9VFEBTK" ignored="0" name="Test" tests="7" failures="1" timestamp="22 Jul 2020 00:57:37 GMT" time="49.367" errors="0">
  <testcase name="loginPageValidationTest" time="0.165" classname="tests.LoginPageTests"/>
  <testcase name="validateProductPage" time="0.04" classname="tests.ProductPageTests"/>
  <testcase name="loginAsStandardUser" time="0.831" classname="tests.LoginPageTests"/>
  <testcase name="clickOnProduct" time="0.309" classname="tests.ProductPageTests"/>
  <testcase name="loginAsLockoutUser" time="0.439" classname="tests.LoginPageTests">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Sorry, this user has been locked out.] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Sorry, this user has been locked out.] but found [Epic sadface: Username and password do not match any user in this service]
	at tests.LoginPageTests.loginAsLockoutUser(LoginPageTests.java:53)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginAsLockoutUser -->
  <testcase name="sortByPriceLowToHigh" time="0.34" classname="tests.ProductPageTests"/>
  <testcase name="loginAsInvalidUser" time="0.421" classname="tests.LoginPageTests"/>
</testsuite> <!-- Test -->
